[package]
name = "sfn"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
image = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tract-onnx = "0.20"
yomo = "0.3"
