[package]
name = "sfn"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# tensorflow = { version = "0.19", features = ["eager"] }
anyhow = "1.0"
image = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tract-onnx = "0.19"
yomo = "0.1"
